Repository bcad1591/airbnb, pull requests merged in 2022-06, with the labels that each got.

#14 [FE] 기본 UI 컴포넌트 구현
  fe/.eslintrc.json
  fe/src/components/Calendar/MonthTable.tsx
  fe/src/components/SearchBar/BigSearchBar/Button.tsx
  fe/src/components/SearchBar/BigSearchBar/DateButton.tsx
  fe/src/components/SearchBar/BigSearchBar/GuestsButton.tsx
  fe/src/components/SearchBar/BigSearchBar/PriceButton.tsx
  fe/src/components/SearchBar/BigSearchBar/index.tsx
  fe/src/components/SearchBar/BigSearchBar/style.ts
  fe/src/components/SearchBar/SmallSearchBar/Button.tsx
  fe/src/components/SearchBar/SmallSearchBar/DateButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/GuestsButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/PriceButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/index.tsx
  fe/src/components/SearchBar/SmallSearchBar/style.ts
  fe/src/components/SearchBar/common.ts
  fe/src/hooks/useFetch/useFetch.tsx
  fe/src/styles/theme.ts
  fe/src/utils/index.ts
Labels: fe, feat

#17 [FE] Price Picker Component 추가
  fe/src/App.tsx
  fe/src/Temp.tsx
  fe/src/apis/accommodation.ts
  fe/src/components/Chart/Drawer.tsx
  fe/src/components/Chart/index.tsx
  fe/src/components/Chart/style.ts
  fe/src/components/Gnb/index.tsx
  fe/src/components/PricePicker/index.tsx
  fe/src/components/PricePicker/style.ts
  fe/src/contexts/Accommodation/index.tsx
  fe/src/hooks/useFetch/useFetch.tsx
  fe/src/index.tsx
  fe/src/mocks/AccommodationData.ts
  fe/src/mocks/handlers.ts
Labels: fe, feat

#22 [FE] InputRangeSlider 리팩토링
  fe/src/components/MultiRangeSlider/LeftInput.tsx
  fe/src/components/MultiRangeSlider/RightInput.tsx
  fe/src/components/MultiRangeSlider/common.ts
  fe/src/components/MultiRangeSlider/context/InputRange/index.tsx
  fe/src/components/MultiRangeSlider/index.tsx
  fe/src/components/MultiRangeSlider/style.ts
Labels: fe, refactor

#24 [FE] Range Slider 변수이름 변경
  fe/src/components/Chart/index.tsx
  fe/src/components/MultiRangeSlider/LeftInput.tsx
  fe/src/components/MultiRangeSlider/RightInput.tsx
  fe/src/components/MultiRangeSlider/common.ts
  fe/src/components/MultiRangeSlider/index.tsx
  fe/src/components/PricePicker/index.tsx
  fe/src/index.tsx
Labels: fe, refactor

#25 [FE] Popup 구현, Home, Search 페이지 일부 구현
  fe/public/assets/fonts/airbnb.svg
  fe/public/assets/fonts/airbnb.ttf
  fe/public/assets/fonts/airbnb.woff
  fe/public/assets/images/home.png
  fe/public/assets/images/sliderThumb.svg
  fe/public/assets/style.css
  fe/src/App.tsx
  fe/src/Temp.tsx
  fe/src/components/AccountMenu/index.tsx
  fe/src/components/AccountMenu/style.ts
  fe/src/components/Chart/bzCurve.ts
  fe/src/components/Gnb/index.tsx
  fe/src/components/Header/hooks/index.tsx
  fe/src/components/Header/index.tsx
  fe/src/components/Header/style.ts
  fe/src/components/MultiRangeSlider/style.ts
  fe/src/components/PricePicker/index.tsx
  fe/src/components/PricePicker/style.ts
  fe/src/components/SearchBar/BigSearchBar/Button.tsx
  fe/src/components/SearchBar/BigSearchBar/DateButton.tsx
  fe/src/components/SearchBar/BigSearchBar/GuestsButton.tsx
  fe/src/components/SearchBar/BigSearchBar/PriceButton.tsx
  fe/src/components/SearchBar/BigSearchBar/index.tsx
  fe/src/components/SearchBar/BigSearchBar/style.ts
  fe/src/components/SearchBar/SmallSearchBar/DateButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/PriceButton.tsx
  fe/src/components/SearchBar/SmallSearchBar/index.tsx
  fe/src/components/SearchBar/common.ts
  fe/src/contexts/Accommodation/index.tsx
  fe/src/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/Home/style.ts
  fe/src/pages/Search/index.tsx
  fe/src/pages/Search/style.ts
  fe/src/styles/styled.d.ts
  fe/src/styles/theme.ts
  fe/tsconfig.json
  fe/webpack.config.js
Labels: fe, feat, refactor

#27 [FE] 버그 수정, 이미지 URL 수정
  fe/src/App.tsx
  fe/src/components/Header/index.tsx
  fe/src/components/MultiRangeSlider/style.ts
  fe/src/components/PricePicker/index.tsx
  fe/src/components/SearchBar/BigSearchBar/index.tsx
  fe/src/contexts/GeoLocation/index.tsx
  fe/src/hooks/useAsync/index.tsx
  fe/src/index.tsx
  fe/src/pages/Home/style.ts
  fe/src/utils/index.ts
  fe/webpack.config.js
Labels: fe, fix, refactor

#28 [FE] default Latitude, Longitude 수정
  fe/src/contexts/GeoLocation/index.tsx
Labels: fe, refactor

#29 [FE] package.json 업데이트
  fe/package-lock.json
  fe/package.json
Labels: fe, chore

#30 [FE] API Response 데이터 명세에 맞게 수정
  fe/src/components/PricePicker/index.tsx
  fe/src/mocks/handlers.ts
Labels: fix

#31 [FE] Chart scaleFactor, maxCount 조절
  fe/src/contexts/Accommodation/index.tsx
  fe/src/mocks/handlers.ts
Labels: fix
